### ISSUE TITLE
test_create_community_with_location fails

### ISSUE THREAD

**Issue by Tinux-18** [dcberlin/map-kit-backend#44]

**Comment by 03b8** [comment]
This seems to be working locally: The test suite is passing and the specific calls that are returning a 403 work when I curl them from my machine. I suspect the [Nominatim API](https://wiki.openstreetmap.org/wiki/Nominatim) (used here as default geocoding API by the [geocoder](https://geocoder.readthedocs.io/) library) is rate limiting or blocking any calls coming from GitHub actions workers. Two possible low effort solutions:
- Mock the Nominatim API response, ugly and easy, does the job
- Switch to using Mapbox in the test, should work out of the box with just setting the `MAPBOX_TOKEN` env var in the CI environment

**Comment by 03b8** [comment]
It looks like I was wrong on this one. I was able to reproduce this locally after all, just had to remove the mapbox token from my local env. Next suspect would be: Geocode library version is outdated and not compatible anymore with the Nominatim API. Updating to the latest should fix it.
