### ISSUE TITLE
Why do we need to migrate on start-up?

### ISSUE THREAD

**Issue by Tinux-18** [dcberlin/map-kit-backend#46]
https://github.com/dcberlin/map-kit-backend/blob/f4217a1e87237a913f2a6c8a102cdf64b742262d/README.md?plain=1#L21

**Comment by 03b8** [comment]
You mean why we have this instruction in the README despite us having migrations happening automatically in the entrypoint script anyway? I assume it's just a relic of the past from the times when we didn't apply migrations on startup.

If the question is rather why we apply migrations on each start-up via the entrypoint script: For convenience. In the past we had the setup where we needed to apply them manually each time we had new ones, and it was cumbersome. If you have something in mind about improving this, or are concerned about specific downsides of the current approach, let's discuss.

**Comment by Tinux-18** [comment]
I was just confused why do we need it in the README. We should remove it.
